# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "ReLER lab"
title:              "as called as Recognition, Learning and Reasoning Lab"
description:        "this is a page for ReLER lab, we are xxxx."


# URL
url:                http://reler.net
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "resources"
    href:           "/resources"
  #- name:           "news"
    #href:           "/news"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
